### ISSUE TITLE
Why useSet is needed in testOperation?

### ISSUE THREAD

**Issue by juanrh** [holdenk/spark-testing-base#6]
Hi, 

Thanks a lot for this package, I find it very interesting. 

The thing is I've been taking a look at `StreamingSuiteBase.testOperation`, and I don't understand how `useSet` works. I understand the input and output are specified as a `Seq` of `Seq`, corresponding to a series of RDDs for a prefix of a DStream. Hence each internal `Seq` is a micro batch. From what I see at `verifyOutput` I understand that each when `useSet` is true then each micro batch is treated like a set, and when it is false then each micro batch is treated like a list. But I understand an RDD is a distributed implementation of a multiset, so I don't get how any of these two interpretations could make sense. Maybe I'm missing something?

Thanks a lot in advance, 

Greetings, 

Juan

**Comment by holdenk** [comment]
Hi Juan, thats a great question and we should probably add an explanation for when you would want to use useSet and when not to the scaladocs.

So RDDs can actual have order information applied to them, in which case you wouldn't want to have useSet=true because you would also want to test the order info.

**Comment by juanrh** [comment]
Hi, 

Thanks a lot for your answer. 

I have to admit I'm still confused, because from your answer I get the impression that my understanding of RDDs is not as good as I though it was. Could you please give me some reference where I could learn more about the order information contained in RDDs? Maybe you refer to OrderedRDDFunctions? But that only applies to RDDs or pairs, as order is defined by the key. Also, even assuming A is used for sorting on RDD[A], if HashPartitioned is used then the order is preserved? Maybe the ordering has something to do with using sort-based shuffle (https://issues.apache.org/jira/browse/SPARK-3280)

Also, for the case when useSet=true, when using toSet you lose repetitions, maybe using a Scala implementation of multisets like for example https://github.com/nicolasstucki/multisets would be a better option. Just my two cents

Thanks a lot for your help. 

Greetings, 

Juan

**Comment by holdenk** [comment]
HI Juan,

Thats a good point, we should probably use MultiSet instead of regular sets. Would you want to make a PR for that (if not no worries I can do it this weekend). For ordering of RDDs I don't really know of any good documentation on it per-se, but if we look at the RDD class we can see the function sortBy ( http://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.rdd.RDD ) which returns an RDD so its clear we can have sorted RDDs. If one was to re-partition the RDD after sorting I think the sort order would be lost.

Cheers,

Holden :)

**Comment by juanrh** [comment]
Hi Holden, 

I will take a look to sortBy, thanks a lot for the reference. I'll be happy to make a PR for MultiSet, if I'm still on time.

Greetings, 

Juan
