### ISSUE TITLE
Unit testing spark jobserver jobs 

### ISSUE THREAD

**Issue by geoHeil** [holdenk/spark-testing-base#99]
How to pass configuration values to a job?

http://stackoverflow.com/questions/36709573/spark-jobserver-unit-testing-of-jobs

**Comment by mahmoudhanafy** [comment]
I think the problem is not related to spark-testing-base library. I found a related question [here](http://stackoverflow.com/questions/33914428/apache-spark-uncaught-exception-in-thread-driver-heartbeater), that may help you.

I worked with spark-jobserver before and we found lots of problems when building and deploying it. I think the problem may be that spark-jobserver didn't deployed correctly.

Also, I think the right place to report this issue is the spark-jobsever [project](https://github.com/spark-jobserver/spark-jobserver/commits/master).

**Comment by geoHeil** [comment]
Sure will report there.
